- alias: Scene selection Tilstede
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Tilstede"
  action:
  - service: scene.turn_on
    entity_id: scene.tilstede

- alias: Scene selection Borte
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Borte"
  action:
  - service: scene.turn_on
    entity_id: scene.borte

- alias: Turn of power usage if smoke is detected
  trigger:
    platform: state
    entity_id: sensor.smoke_sensor_smoke_2
    to: '255'
  action:
  - service: scene.turn_on
    entity_id: scene.borte

- alias: Send message when smoke is detected
  trigger:
    platform: state
    entity_id: sensor.smoke_sensor_smoke_2
    to: '255'
  action:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.scene_status_dropdown
      state: 'Borte'   
  - service: notify.ios_iphonetg
    data:
      message: Røykvasleren er utløst for røyk
      data:
          push:
            badge: 5

- alias: Turn of power usage when excessive heat detected
  trigger:
    platform: state
    entity_id: sensor.smoke_sensor_heat_2
    to: '255'
  action:
  - service: scene.turn_on
    entity_id: scene.borte

- alias: Send message when excessive heat detected
  trigger:
    platform: state
    entity_id: sensor.smoke_sensor_heat_2
    to: '255'
  action:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.scene_status_dropdown
      state: 'Borte'   
  - service: notify.ios_iphonetg
    data:
      message: Røykvasleren er utløst for varme
      data:
          push:
            badge: 5

- alias: Notify if door is opened while cabin in status Borte
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor
    to: 'on'
  action:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.scene_status_dropdown
      state: 'Borte'   
  - service: notify.ios_iphonetg
    data:
      message: Døra på hytta ble åpnet 
      data:
          push:
            badge: 5


- alias: Set theromstat values when tilstede scene is set
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Tilstede"
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.bedroom_thermostat_heating
      temperature: 15
  - service: climate.set_temperature
    data:
      entity_id: climate.hall_thermostat_heating
      temperature: 23
      operation_mode: Heat
  - service: climate.set_temperature
    data:
      entity_id: climate.livingroom_thermostat_heating
      temperature: 23
      operation_mode: Heat

- alias: Set theromstat values when borte scene is set
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Borte"
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.bedroom_thermostat_heating
      temperature: 11
  - service: climate.set_temperature
    data:
      entity_id: climate.hall_thermostat_heating
      temperature: 11
      operation_mode: Heat
  - service: climate.set_temperature
    data:
      entity_id: climate.livingroom_thermostat_heating
      temperature: 11
      operation_mode: Heat

- alias: Turn on cable heating well morning
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - switch.cable_heating_well_switch    

- alias: Turn off cable heating well morning
  trigger:
    platform: time
    at: '09:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - switch.cable_heating_well_switch    

- alias: Turn on cable heating well evening
  trigger:
    platform: time
    at: '19:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - switch.cable_heating_well_switch    

- alias: Turn off cable heating well evening
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - switch.cable_heating_well_switch    


