- alias: Scene selection Tilstede
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Tilstede"
  action:
  - service: scene.turn_on
    entity_id: scene.tilstede

- alias: Scene selection Borte
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Borte"
  action:
  - service: scene.turn_on
    entity_id: scene.borte

- alias: Turn of power usage if smoke is detected
  trigger:
    platform: state
    entity_id: sensor.smoke_sensor_smoke
    to: '255'
  action:
  - service: scene.turn_on
    entity_id: scene.borte

- alias: Turn of power usage when excessive heat detected
  trigger:
    platform: state
    entity_id: sensor.smoke_sensor_heat
    to: '255'
  action:
  - service: scene.turn_on
    entity_id: scene.borte

- alias: Notify if door is openes while cabin in status Borte
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor
    to: 'on'
  action:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.scene_status_dropdown
      state: 'Borte'   
  - service: scene.turn_on
    entity_id: scene.tilstede

- alias: Set theromstat values when tilstede scene is set
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Tilstede"
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.bedroom_thermostat_heating
      temperature: 16
  - service: climate.set_temperature
    data:
      entity_id: climate.hall_thermostat_heating
      temperature: 18
      operation_mode: Heat
  - service: climate.set_temperature
    data:
      entity_id: climate.livingroom_thermostat_heating
      temperature: 20
      operation_mode: Heat

- alias: Set theromstat values when borte scene is set
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Borte"
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.bedroom_thermostat_heating
      temperature: 11
  - service: climate.set_temperature
    data:
      entity_id: climate.hall_thermostat_heating
      temperature: 11
      operation_mode: Heat
  - service: climate.set_temperature
    data:
      entity_id: climate.livingroom_thermostat_heating
      temperature: 11
      operation_mode: Heat
