- id: Scene_selection_Tilstede
  alias: Scene selection Tilstede
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Tilstede"
  action:
  - service: scene.turn_on
    entity_id: scene.tilstede

- id: Scene_selection_Borte
  alias: Scene selection Borte
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Borte"
  action:
  - service: scene.turn_on
    entity_id: scene.borte

- id: Turn_of_power_usage_if_smoke_is_detected
  alias: Turn of power usage if smoke is detected
  trigger:
    platform: state
    entity_id: sensor.smoke_sensor_smoke_2
    to: '255'
  action:
  - service: scene.turn_on
    entity_id: scene.borte

- id: Send_message_when_smoke_is_detected
  alias: Send message when smoke is detected
  trigger:
    platform: state
    entity_id: sensor.smoke_sensor_smoke_2
    to: '255'
  action:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.scene_status_dropdown
      state: 'Borte'   
  - service: notify.ios_iphonetg
    data:
      message: Røykvasleren er utløst for røyk
      data:
          push:
            badge: 5

- id: Turn_of_power_usage_when_excessive_heat_detected
  alias: Turn of power usage when excessive heat detected
  trigger:
    platform: state
    entity_id: sensor.smoke_sensor_heat_2
    to: '255'
  action:
  - service: scene.turn_on
    entity_id: scene.borte

- id: Send_message_when_excessive_heat_detected
  alias: Send message when excessive heat detected
  trigger:
    platform: state
    entity_id: sensor.smoke_sensor_heat_2
    to: '255'
  action:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.scene_status_dropdown
      state: 'Borte'   
  - service: notify.ios_iphonetg
    data:
      message: Røykvasleren er utløst for varme
      data:
          push:
            badge: 5

- id: Notify_if_door_is_opened_while_cabin_in_status_Borte
  alias: Notify if door is opened while cabin in status Borte
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor
    to: 'on'
  action:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.scene_status_dropdown
      state: 'Borte'   
  - service: notify.ios_iphonetg
    data:
      message: Døra på hytta ble åpnet 
      data:
          push:
            badge: 5


- id: Set_theromstat_values_when_tilstede_scene_is_set
  alias: Set theromstat values when tilstede scene is set
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Tilstede"
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.bedroom_thermostat_heating
      temperature: 15
      hvac_mode: heat
  - service: climate.set_temperature
    data:
      entity_id: climate.hall_thermostat_heating
      temperature: 23
      hvac_mode: heat
  - service: climate.set_temperature
    data:
      entity_id: climate.livingroom_thermostat_heating
      temperature: 23
      hvac_mode: heat

- id: Set_theromstat_values_when_borte_scene_is_set
  alias: Set theromstat values when borte scene is set
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Borte"
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.bedroom_thermostat_heating
      temperature: 11
      hvac_mode: heat
  - service: climate.set_temperature
    data:
      entity_id: climate.hall_thermostat_heating
      temperature: 11
      hvac_mode: heat
  - service: climate.set_temperature
    data:
      entity_id: climate.livingroom_thermostat_heating
      temperature: 11
      hvac_mode: heat

- id: Turn_on_cable_heating_well_morning
  alias: Turn on cable heating well morning
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - switch.cable_heating_well_switch    

- id: Turn_off_cable_heating_well_morning
  alias: Turn off cable heating well morning
  trigger:
    platform: time
    at: '09:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - switch.cable_heating_well_switch    

- id: Turn_on_cable_heating_well_evening
  alias: Turn on cable heating well evening
  trigger:
    platform: time
    at: '19:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - switch.cable_heating_well_switch    

- id: Turn_off_cable_heating_well_evening
  alias: Turn off cable heating well evening
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - switch.cable_heating_well_switch    

- id: Turn_on_toilett_heating_under_8
  alias: Turn on toilett heating under 8
  trigger:
    platform: numeric_state
    entity_id: sensor.toalett_temperature
    below: '8'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - switch.toilet_heater   


######zigbee2mqtt#####
- id: zigbee_enable_join
  alias: Enable Zigbee joining
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.zigbee_permit_join
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee_permit_join
      
- id: zigbee_disable_join
  alias: Disable Zigbee joining
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel
  hide_entity: true
  
- id: disable_zigbee_join_timer
  alias: Disable Zigbee joining by timer
  hide_entity: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join

- id: zigbee_update_networkmap
  alias: 'oppdater Zigbee Map '  
  hide_entity: true  
  trigger:
    platform: time_pattern
    minutes: '/10'
    seconds: 00
  action:
    service: zigbee2mqtt_networkmap.update