- alias: Scene selection Tilstede
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Tilstede"
  action:
  - service: scene.turn_on
    entity_id: scene.tilstede

- alias: Scene selection Borte
  trigger:
    platform: state
    entity_id: input_select.scene_status_dropdown
    to: "Borte"
  action:
  - service: scene.turn_on
    entity_id: scene.borte
