homeassistant:
#  name: Fjellbu
#  latitude: !secret latitude
#  longitude: !secret longitude
#  elevation: 948
#  unit_system: metric
#  time_zone: Europe/Oslo
  customize: !include customize.yaml

# Enables the frontend
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/lovelace.html

config:
system_health:
zigbee2mqtt_networkmap:

panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'    

recorder:
  purge_keep_days: 7
  
http:
  base_url: !secret ha_url
  
updater:
discovery:
conversation:
history:
logbook:
map:
sun:
mobile_app:
#apple_tv: 

# Zwave 
zwave:
  usb_path: /dev/ttyACM1
  
# Weather prediction
#sensor:
#  - platform: yr

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:


#camera:
#  - platform: generic
#    name: Meteogram
#    still_image_url: https://www.yr.no/place/Norway/Buskerud/Nes/Fj%C3%B8laset/meteogram.svg
#    content_type: 'image/svg+xml'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
input_select: !include_dir_merge_named input_select
scene: !include scene.yaml
sensor: !include sensor.yaml
timer: !include timer.yaml
input_boolean: !include input_boolean.yaml
