- platform: template
  sensors:
    smoke_alarm:
      friendly_name: 'Røykvarsler'
      value_template: >-
        {% if is_state("sensor.smoke_sensor_smoke_2", "255") %}
          Alarm utløst røyk
        {% elif is_state("sensor.smoke_sensor_heat_2", "255") %}
          Alarm utløst varme          
        {% elif is_state("sensor.smoke_sensor_burglar", "3") %}
          Ikke montert
        {% else %}
          Normal
        {% endif %} 

- platform: yr

#uptime sensor
- platform: uptime
  name: Time Online
  unit_of_measurement: hours

#System monitor sensors  
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use

#####zigbee2mqtt#######
- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless

####Ipadresse####
- platform: dnsip