- platform: template
  sensors:
    smoke_alarm:
      friendly_name: 'Røykvarsler'
      value_template: >-
        {% if is_state("sensor.smoke_sensor_smoke_2", "255") %}
          Alarm utløst røyk
        {% elif is_state("sensor.smoke_sensor_heat_2", "255") %}
          Alarm utløst varme          
        {% elif is_state("sensor.smoke_sensor_burglar", "3") %}
          Ikke montert
        {% else %}
          Normal
        {% endif %} 

- platform: yr
