- platform: template
  sensors:
    smoke_alarm:
      friendly_name: 'Røykvarsler'
      value_template: >-
        {% if is_state("sensor.smoke_sensor_alarm_level", "255") %}
          Alarm utløst
        {% elif is_state("sensor.smoke_sensor_burglar", "3") %}
          Ikke montert
        {% else %}
          Normal
        {% endif %} 

- platform: yr
